development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: tadoku_dev
  pool: 5
  username: postgres
  password: 
test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: tadoku_test
  pool: 5
  username: postgres
  password:
