# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d95441f43a61ea67be9b5a3b00847611fef6bfed79b5ce38c7cddaddbb581f84d5d3d6485df70154cf4cad272b563e566d356eeae20dc6afb313d5a6e206672

test:
  secret_key_base: c049f7181a2ab3c3fd038ed669351c2531629884f4765e60cb833d15c284c0c58d15ab4c8024c45c7c2a4d704d1631e218d62996657b53b44e2cd0ead0207fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
